"""2nd commit

Revision ID: 5ca36a28de78
Revises: f2e443a7bd9b
Create Date: 2024-10-26 12:26:52.585096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca36a28de78'
down_revision: Union[str, None] = 'f2e443a7bd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowed_books', sa.Column('book_id', sa.Integer(), nullable=False))
    op.add_column('borrowed_books', sa.Column('reader_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'borrowed_books', 'books', ['book_id'], ['id'])
    op.create_foreign_key(None, 'borrowed_books', 'readers', ['reader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'borrowed_books', type_='foreignkey')
    op.drop_constraint(None, 'borrowed_books', type_='foreignkey')
    op.drop_column('borrowed_books', 'reader_id')
    op.drop_column('borrowed_books', 'book_id')
    # ### end Alembic commands ###
